import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Banner from "./components/banner";
import Categories from "./components/categories";
import FeaturedProducts from "./components/featureProduts";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Navbar/>
      <Banner/>
      <Categories/>
      <FeaturedProducts/>
      <Footer/>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
